global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    otus: go

remote_write:
  - url: http://victoriametrics:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
rule_files:
  - rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "victoriametrics"
    static_configs:
      - targets: ["victoriametrics:8428"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "simple-app"
    scrape_interval: 15s
    static_configs:
      - targets: ["simple-app:8080"]

  - job_name: "postgresql"
    scrape_interval: 15s
    static_configs:
      - targets: ["postgresql-exporter:9187"]
